[phases.setup]
nixPkgs = ["nodejs", "python3", "python3Packages.pip"]

[phases.install]
cmds = [
    "npm install",
    "npm run build",
    "pip install -r requirements.txt"
]

[start]
cmd = "python app.py"
